version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  graylog:
    image: graylog/graylog:5.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=2bb80d5... # sha256 for 'admin'
      - GRAYLOG_HTTP_EXTERNAL_URI=http://10.0.2.16:9000/
    depends_on:
      - mongodb
      - opensearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"

  datapreper:
    image: graylog/graylog-datapreper:latest
    ports:
      - "9999:9999"