
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - "5601:5601"
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.17.3
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
