version: '3.8'

services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    volumes:
      - ./consul/server.json:/consul/config/server.json

  postgres1:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgbouncer:
    image: edoburu/pgbouncer
    volumes:
      - ./database/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    ports:
      - "6432:6432"

  nginx:
    image: nginx
    volumes:
      - ./wordpress/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  wordpress:
    image: wordpress:php8.1-fpm
    environment:
      - WORDPRESS_DB_HOST=postgres1
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana

  loki:
    image: grafana/loki
    volumes:
      - ./monitoring/loki/config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail
    volumes:
      - ./logging/promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    depends_on:
      - loki