global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'

    - match:
        severity: warning
      receiver: 'warning-receiver'

receivers:
  - name: 'critical-receiver'
    webhook_configs:
      - url: 'https://webhook.site/7e4879f6-6db3-497c-adc3-1332295895fa'

  - name: 'warning-receiver'
    webhook_configs:
      - url: 'https://webhook.site/889ed0de-bfc4-4906-827b-285394038331'

  - name: 'default'
    webhook_configs:
      - url: 'https://webhook.site/734ae8be-cddf-4479-ac7a-25a67755a364'


