global:
  scrape_interval: 15s
  external_labels:
    site: prod

remote_write:
  - url: "http://localhost:8428/api/v1/write"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - target_label: 'site'
        replacement: 'prod'  # Добавление лейбла site=prod

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
    relabel_configs:
      - target_label: 'site'
        replacement: 'prod'

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['localhost:9104']
    relabel_configs:
      - target_label: 'site'
        replacement: 'prod'

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx_with_redirect]
    static_configs:
      - targets:
          - https://ru.wordpress.org/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
      - target_label: 'site'
        replacement: 'prod'
